### ISSUE TITLE
backup.py "TypeError: Expected a list of bytes"

### ISSUE THREAD

**Issue by chozian** [LedgerHQ/ledger-app-openpgp-card#22]
The following error is received when executing the original backup.py or the modified code at https://github.com/LedgerHQ/blue-app-openpgp-card/issues/8#issuecomment-334121837.

```
# python backup.py 
Traceback (most recent call last):
  File "backup.py", line 20, in <module>
    gpgcard.get_all()
  File "/home/chozian/git/ledger/blue-app-openpgp-card/pytools/gpgcard/gpgcard.py", line 221, in get_all
    self.AID,sw                      = self.get_data(0x4f)
  File "/home/chozian/git/ledger/blue-app-openpgp-card/pytools/gpgcard/gpgcard.py", line 189, in get_data
    return self.exchange(apdu)
  File "/home/chozian/git/ledger/blue-app-openpgp-card/pytools/gpgcard/gpgcard.py", line 156, in _exchange_pcsc
    resp, sw1, sw2 = self.connection.transmit(apdu)
  File "/usr/lib/python2.7/dist-packages/smartcard/CardConnectionDecorator.py", line 82, in transmit
    return self.component.transmit(bytes, protocol)
  File "/usr/lib/python2.7/dist-packages/smartcard/CardConnection.py", line 146, in transmit
    data, sw1, sw2 = self.doTransmit(bytes, protocol)
  File "/usr/lib/python2.7/dist-packages/smartcard/pcsc/PCSCCardConnection.py", line 200, in doTransmit
    self.hcard, pcscprotocolheader, bytes)
  File "/usr/lib/python2.7/dist-packages/smartcard/scard/scard.py", line 850, in SCardTransmit
    return _scard.SCardTransmit(hcard, pioSendPci, apducommand)
TypeError: Expected a list of bytes.
```

**Versions:**
- Ledger OpenPGP, Spec 3.3.1, App 1.1.1 installed using Ledger Manager
- https://github.com/LedgerHQ/blue-app-openpgp-card, branch 1.1.0_fw.1.4.1, commit 81090d3f235a294e3f72879f4d889a3512a4e227
- https://github.com/LedgerHQ/udev-rules, branch master, commit 681cd1346f2dd5bc3ab19a7985caabbc97e1861b

This was tested using 2 different Ledger Nano S units with firmware 1.4.1. The results were the same for both.

The latest releases of blue-loader-python, blue-app-ssh-agent, blue-app-u2f, and trezor-agent all work as expected.

This was tested with and without PGP keys generated on the Ledgers.

gpg --card-status and --card-edit work as expected, except when generating 4096 RSA keys which results in a failure. 3072 RSA keys generate without issue though.

This was tested using Debian 8 on VirtualBox 5.2.8 and VMware Workstation 14 Player.

**Debian 8 Package Versions:**
- libccid_1.4.29-2_amd64.deb

**Debian 8 python virtualenv:**

- argparse (1.2.1)
- certifi (2018.1.18)
- chardet (3.0.4)
- Cython (0.28.1)
- ECPy (0.8.1)
- future (0.16.0)
- hidapi (0.7.99.post21)
- idna (2.6)
- ledgerblue (0.1.17)
- Pillow (5.1.0)
- pip (1.5.6)
- protobuf (3.5.2.post1)
- pycrypto (2.6.1)
- pyscard (1.9.6)
- python-u2flib-host (3.0.3)
- requests (2.18.4)
- setuptools (39.0.1)
- six (1.11.0)
- urllib3 (1.22)
- wsgiref (0.1.2)

This was also tested using Ubuntu 16.04 LTS on a bare metal Dell Latitude with built-in smart card reader and Dell Inspiron with no other smart card reader.

**Ubuntu Package Versions:**
- libccid_1.4.29-1_amd64.deb

**Ubuntu python virtualenv:**

- certifi            2018.1.18    
- chardet            3.0.4        
- ECPy               0.8.1        
- future             0.16.0       
- hidapi             0.7.99.post21
- idna               2.6          
- ledgerblue         0.1.17       
- Pillow             5.1.0        
- pip                10.0.0       
- pkg-resources      0.0.0        
- protobuf           3.5.2.post1  
- pycrypto           2.6.1        
- python-u2flib-host 3.0.3        
- requests           2.18.4       
- setuptools         39.0.1       
- six                1.11.0       
- urllib3            1.22         
- wheel              0.31.0
- pyscard 1.9.6 via pip, and 1.6.12 via python-pyscard_1.6.12.1-5_amd64.deb with /usr/lib/python2.7/dist-packages added to the python path

pcsc_scan displays the following.

```
PC/SC device scanner
V 1.4.25 (c) 2001-2011, Ludovic Rousseau <ludovic.rousseau@free.fr>
Compiled with PC/SC lite version: 1.8.14
Using reader plug'n play mechanism
Scanning present readers...
0: Ledger Nano S [Nano S] (0001) 00 00
1: Broadcom Corp 5880 [Contacted SmartCard] (0123456789ABCD) 01 00

Sun Apr 15 22:02:08 2018
Reader 0: Ledger Nano S [Nano S] (0001) 00 00
  Card state: Card inserted, 
  ATR: 3B 00

ATR: 3B 00
+ TS = 3B --> Direct Convention
+ T0 = 00, Y(1): 0000, K: 0 (historical bytes)
Reader 1: Broadcom Corp 5880 [Contacted SmartCard] (0123456789ABCD) 01 00
  Card state: Card removed,
```

I am not sure if the following dmesg output is relevant to this issue. The two lines containing "interface number" as shown below occur when switching to the OpenPGP app on the Ledger.

```
[ 7084.929065] usb 2-1.4: new full-speed USB device number 5 using ehci-pci
[ 7085.043198] usb 2-1.4: config 1 has an invalid interface number: 2 but max is 1
[ 7085.043206] usb 2-1.4: config 1 has no interface number 1
[ 7085.047244] usb 2-1.4: New USB device found, idVendor=2c97, idProduct=0001
[ 7085.047253] usb 2-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 7085.047258] usb 2-1.4: Product: Nano S
[ 7085.047262] usb 2-1.4: Manufacturer: Ledger
[ 7085.047266] usb 2-1.4: SerialNumber: 0001
[ 7085.054911] hid-generic 0003:2C97:0001.0003: hiddev0,hidraw0: USB HID v1.11 Device [Ledger Nano S] on usb-0000:00:1d.0-1.4/input0
```

Please let me know if any additional information would be useful. I would like to know if the error with backup.py is due to a bug. Am I simply overlooking something? I feel like I have thoroughly exhausted all troubleshooting options based on my knowledge and experience at this point. Anyone's assistance would be greatly appreciated. Thanks!

**Comment by chozian** [comment]
The reason I would really like to get this working is to have a way to restore my seed-generated keys after a Ledger Nano S firmware upgrade. If there is a better method, please let me know. Thanks!

**Comment by cslashm** [comment]
Did you try python3?
