### ISSUE TITLE
Disable 'GET DATA' on private key DOs

### ISSUE THREAD

**Issue by jpathy** [LedgerHQ/ledger-app-openpgp-card#28]
Hello, as i see here: 
https://github.com/LedgerHQ/blue-app-openpgp-card/blob/c07cb00cb61035fe13af668c3caf11f2ea0af044/src/gpg_data.c#L43-L55
the private key DOs are readable, i believe this shouldn't be possible for pgpcards, the seeded mode should be used, if this property is desired.

**Comment by cslashm** [comment]
that's not private key. Just private user data, not used by gnupg
