### ISSUE TITLE
Cannot change PIN mode

### ISSUE THREAD

**Issue by 1989gironimo** [LedgerHQ/ledger-app-openpgp-card#30]
If I try to change the PIN mode to Host or OnScreen the ledger nano s just says "User PIN not verified".
"Admin PIN not verified" is the message I got if I want to change it to "Trust"

Both messages aren't really documented, so what's the meaning of them?

**Comment by sg495** [comment]
On Ubuntu 18.04, what worked for me was opening `gpg --card-edit`, enabling `admin` and then using `verify`. Once the user/admin PIN has been entered on the computer, I was allowed to change PIN mode. Not that it made any material difference, though (see #31).

**Comment by 1989gironimo** [comment]
Nice workaround, it work's!
