### ISSUE TITLE
Will keys be removed upon app removal?

### ISSUE THREAD

**Issue by luginbash** [LedgerHQ/ledger-app-openpgp-card#33]
Hi,

I'm having a question about the persistence of my PGP keys generated by the applet: Will I lose the key if I remove and install the app again? 

The reason why I'm doing this is if I directly install the app, the ledger manager will complain about "insufficient space left on device".

Regards,

Luginbash

**Comment by nyanloutre** [comment]
Yes keys are gone when you uninstall the app, you need a backup

**Comment by luginbash** [comment]
Understood. Thanks clearing things up!
