### ISSUE TITLE
-XL version for Nano S

### ISSUE THREAD

**Issue by NiklausHofer** [LedgerHQ/ledger-app-openpgp-card#38]
For the Ledger Nano S, the version available from Ledger Live only has a single slot. This used to be different in version 1.1.0 where the app features 3 slots. I can see now that there is an -XL version of the app, apparently available for Ledger Blue, that has 3 slots. Unfortunately, I was unable to find an explanation of why the multi-slot option was removed. Could you maybe offer both the regular and the -XL version for the Nano S in Ledger Live?

**Comment by NiklausHofer** [comment]
I can report that 4K RSA keys are not working with the OpenPGP.XL app on the Ledger Nano S. The key loads from the PC to the card just fine, but when doing operations with it, a card error gets reported:

```
gpg --decrypt foo.txt.crypt.4k
```
```
gpg: encrypted with 4096-bit RSA key, ID 658553032EEA115F, created 2018-12-02
      "xmpp:max.muster@example.com"
gpg: public key decryption failed: Card error
gpg: decryption failed: No secret key
```

```
gpg --local-user 'C5F9BBBC4DBDAAAF!' --output foo.txt.sig.4k --sign foo.txt
```

```
gpg: signing failed: Card error
gpg: signing failed: Card error
```

Here is what I know about this:
* I have yet to test 4k RSA keys on the regular version of the app
* I tried putting the RSA key in any of the 3 Slots. The effect is always the same
* It works just fine with ed25519
    * ed25519 keys still work correctly, even when there is an RSA 4K key in any other of the slots
* I have yet to test smaller RSA keys

**Comment by NiklausHofer** [comment]
I have tested it with the regular version of the app (OpenPGP rather than OpenPGP.XL) today. I am getting the same error when using 4K RSA keys. So the problem might be with the app in general or with my development environment, but probably not with the Multislot mode in particular.

I will test the official version of the app next, the one from Ledger Live.

**Comment by NiklausHofer** [comment]
It works just fine with the official version from the Ledger Live app. So there is most likely something wrong with the way I build the application.

Could you help me figure out what it is? Here is what I am using in my development VM:
* Ubuntu 18.04 amd64
* [Nano S Secure SDK](https://github.com/LedgerHQ/nanos-secure-sdk) on tag [nanos-1421](https://github.com/LedgerHQ/nanos-secure-sdk/releases/tag/nanos-1421)
* Clang version 4.0, the '[Clang for x86_64 Debian 8](https://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-linux-gnu-debian8.tar.xz)' prebuilt binary
* The latest commit of this app

Any ideas?

**Comment by nyanloutre** [comment]
I tried to generate 4K RSA keys with seeded mode enabled on the version from Ledger live and it's returning an error.

Without seeded mode I get no error.

**Comment by cslashm** [comment]
@NiklausHofer XL 1.3.1 released
