### ISSUE TITLE
UIF not working for decryption

### ISSUE THREAD

**Issue by NiklausHofer** [LedgerHQ/ledger-app-openpgp-card#39]
I have UIF enabled for all options (a `+` symbol is showing up in each row) and it works fine for 'authentication' and 'signature'. That is to say, when I use SSH and when I am signing an E-Mail, the Ledger Nano S asks me to confirm the action, as one would expect. However, it does not seem to be working with decryption. E-Mails decrypt instantly, without me being asked to confirm the action.

I am sure to not have a different token installed for the key. I am also sure that the secret key is not installed locally on my machine. When I try decrypting an E-Mail while the token is not plugged in, I am asked to insert the token.

**Comment by Mansarde** [comment]
I can confirm this for decrypting files on Linux (Ubuntu 18.04).

If decryption was confirmed once, then as long as the connection to the Ledger is not reset (by e.g. executing `gpg-connect-agent killagent /bye` or simply re-entering the app on the device),
then no further confirmation is asked for subsequent decryption attempts.
Instead it seems the Ledger is practically in "Trust" mode after the first confirmation.

**Comment by cslashm** [comment]
fixed in 1.3.1
