### ISSUE TITLE
Reader name change

### ISSUE THREAD

**Issue by mlapaj** [LedgerHQ/ledger-app-openpgp-card#43]
It seems that reader name has changed. I had to update scdaemon.conf file
from:
reader-port "Ledger Token [Nano S] (0001) 01 00"
to: 
reader-port "Ledger Nano S [Nano S] (0001) 01 00"

I have a laptop with integrated usb broadcom sc reader. So without this fix, scdaemon and pscscd was using internal broadcom reader.

Can someone confirm name change in ledger FW and update or add some note to documentation ? 

BR,
Marcin

**Comment by cslashm** [comment]
Yes reader has changed in last SDK.

pcsc_scan is the tool to identify your device
