### ISSUE TITLE
Restoring non-seed keys from backup failed

### ISSUE THREAD

**Issue by Mansarde** [LedgerHQ/ledger-app-openpgp-card#44]
Hey @cslashm 
Today I ugraded my Nano S to the new firmware v1.5.5
Before the upgrade these were the versions I used:
Firmware v1.4.2
OpenPGP v1.3.0

Before upgrading I backed up my keys with the script using this command:
`python3 -m gpgcard.gpgcli --pinpad --backup --backup-keys`

I verified, multiple times, that restoring the keys works by executing...
`python3 -m gpgcard.gpgcli --pinpad --restore`
... and signing & decrypting files successfully.

After upgrading to the new firmware and re-installing OpenPGP I wanted to restore my keys.
The pickle file was still where I left it, so I tried to execute:
`python3 -m gpgcard.gpgcli --pinpad --restore`

But now this error appears:
```
Restore Application...Error:
  (b'00000002', '6f42')
```
After checking `gpg --card-status` it looks like the keys have been restored successfully though.
At least it shows exactly the same data, including the correct fingerprints I had before.
And the Nano S shows the correct ID as well in the display.

But if I try to decrypt or sign something, then after entering the PIN it tells me that I don't have the secret key.

Are pickle files created with firmware 1.4.2 incompatible with firmware 1.5.5?

**Comment by mlapaj** [comment]
I have similar problem with doing backup. Doing backup without private keys is working fine. 
When i do backup with private keys I got similar error. 6f42 
Basically there is a problem with get/set data from 0x00B6, 0x00B8, 0x00A4 - sig_key, dec_key, aut_key backuping  / storing.

I`ll try to investigate it in free time.

**Comment by cslashm** [comment]
Picke should be compatible.
I think your problem is the crypto export restriction for non Ledger-signed app.
1.3.1 is coming

**Comment by Mansarde** [comment]
That's good news, looking forward to it!  :)

**Comment by Mansarde** [comment]
@cslashm I just loaded OpenPGP v1.3.1 into my Ledger via the SDK.
Unfortunately after trying to restore my keys I still get an error message, but a little bit different than before.

Trying to restore from OpenPGP v1.3.0 installed via Ledger Live yielded:
```
Restore Application...Error:
  (b'00000002', '6f42')
```
Trying to restore from OpenPGP v1.3.1 installed via SDK now yields:
```
Restore Application...Error:
  (b'00000011', '6f42')
```

I.e. instead of `b'00000002'` it is now `b'00000011'`.
Is that just because of the version difference of the app or because I loaded it via the SDK?

**Comment by cslashm** [comment]
@Mansarde 1.3.1 released

please provide me commande used to backup/restore in case of problem, plus key type used

**Comment by Mansarde** [comment]
Hi @cslashm 

I just installed v1.3.1 from Ledger Live and tried to restore the keys again.
And this time it worked! I can decrypt again and even the UIF settings seem functional now! :D

It's weird that it didn't work when I tried to install v1.3.1 via the SDK though.
I'll give it another try via the SDK sometime later today, but is there something special I have to do with the SDK version of OpenPGP?

---
Anyways, if you'd still like to know the answers to your questions, here you go:

Key type used:
**non-seed, rsa4096** for all three keys (i.e. sign, authenticate, encrypt)

Command used to backup the keys:
`python3 -m gpgcard.gpgcli --pinpad --backup --backup-keys`
This created the file called `gpg_backup_slot1.pickle`

Command to restore the keys:
`python3 -m gpgcard.gpgcli --pinpad --restore`
I also tried to provide the filename explicitly via:
`python3 -m gpgcard.gpgcli --pinpad --restore --file gpg_backup`

I backed the keys up on OpenPGP v1.3.0 (with firmware 1.4.2).
I tried to restore on OpenPGP v1.3.0 (firmware 1.5.5) which resulted in the mentioned error.
I tried to restore on OpenPGP v1.3.1 via SDK (firmware 1.5.5) which also resulted in the aforementioned error.
Only after restoring on OpenPGP v1.3.1 via Ledger Live (firmware 1.5.5) did it work. :)

---
Thanks for the help, really appreciated! 👍

**Comment by cslashm** [comment]
@Mansarde Happy to see it works!
You cannot really used GPG compiled by your own as AES/DES/RSA are not available for non genuine applications (Provide in Live). This is because of some law concerning cryptography export between France and foreing country

Thanks for your feedback

 @mlapaj  I close this bug as original pb is resolved. Open another one if your still in trouble with detail config and commands used.

**Comment by Mansarde** [comment]
Ah, gotcha, good to know, thx for everything! :)

**Comment by bkdddye5455** [comment]
I upgraded my Nano S and now I cannot restore.  Losing my mind.  Entered Pass Phrase (24) all correctly, pin code, great, everything looks good except non of my accounts come up.  What in the world can I do next.  I'm getting worried.  Thanks
