### ISSUE TITLE
Restore seed mode RSA keys without Ledger

### ISSUE THREAD

**Issue by nyanloutre** [LedgerHQ/ledger-app-openpgp-card#5]
Hi,

The seed mode work really great when I try to wipe my Ledger and generate the keys again. What would be awesome is a script that could restore my RSA keys from my seed in the event my Ledger is broken or stolen.

Keep the good work!
Paul

**Comment by amougel** [comment]
You can use the https://iancoleman.github.io/bip39/ or follow the instructions here : http://support.ledgerwallet.com/knowledge_base/topics/what-happens-if-i-lose-my-ledger-wallet

**Comment by cslashm** [comment]
I am not sure to understand what you want. 
There is no correlation between seeded key and gpg key passphrase.  Could you be more precise about what you want to do.

**Comment by nyanloutre** [comment]
With passphrase I meant the seed, I will edit my comment

**Comment by cslashm** [comment]
I hope to provide a GUI tool to admin the application  in the next release. I will to integrate such feature.

**Comment by cslashm** [comment]
I let this issue open until GUI provides such feature.

**Comment by cslashm** [comment]
GUI postponed to..."Soon (tm)"
