### ISSUE TITLE
Add doc about restoring seeded key

### ISSUE THREAD

**Issue by cslashm** [LedgerHQ/ledger-app-openpgp-card#9]

**Comment by diffusae** [comment]
Hi!

That would be great. It's exactly, what I am missing. I wasn't able to restore seeded keys, after I do reset of the device. Maybe you have a hint? I looks like, that it doesn't work automatically after recovering from the Ledger global token.

Regards

**Comment by diffusae** [comment]
If you like, I could support you with the documentation. First I need to know, how it works.

**Comment by cslashm** [comment]
Great! I'll contact you in the middle of next week.
